'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ChevronLeft, ChevronRight, Plus } from 'lucide-react'
import {
  addDays,
  formatDuration,
  phaseMeta,
  seasonBlocks,
  sportMeta,
  startOfWeek,
  today,
  todayKey,
  workoutsInRange,
  type PhaseKind,
  type Workout,
} from '@/lib/mock-data'
import { PageHeader } from '@/components/kit'
import { WorkoutCard } from '@/components/workout-card'

function keyOf(d: Date) {
  return d.toISOString().slice(0, 10)
}

function phaseForDate(dateKey: string): { label: string; kind: PhaseKind } | null {
  const b = seasonBlocks.find((blk) => dateKey >= blk.startDate && dateKey <= blk.endDate)
  return b ? { label: phaseMeta[b.kind].label, kind: b.kind } : null
}

export function CalendarView() {
  const [weekOffset, setWeekOffset] = useState(0)
  const baseMonday = startOfWeek(today)

  const week = useMemo(() => {
    const monday = addDays(baseMonday, weekOffset * 7)
    const days = Array.from({ length: 7 }, (_, i) => addDays(monday, i))
    const startKey = keyOf(days[0])
    const endKey = keyOf(days[6])
    const all = workoutsInRange(startKey, endKey)
    const byDay = days.map((d) => {
      const k = keyOf(d)
      const items = all.filter((w) => w.date === k)
      const sessions = items.filter((w) => w.sport !== 'rest')
      const plannedTss = sessions.reduce((s, w) => s + w.plannedTss, 0)
      const doneTss = sessions.reduce((s, w) => s + (w.completed?.tss ?? 0), 0)
      const plannedMin = sessions.reduce((s, w) => s + w.plannedDurationMin, 0)
      return { date: d, key: k, items, plannedTss, doneTss, plannedMin }
    })
    const weekTss = byDay.reduce((s, d) => s + d.plannedTss, 0)
    const weekMin = byDay.reduce((s, d) => s + d.plannedMin, 0)
    const phase = phaseForDate(startKey)
    return { monday, days, byDay, weekTss, weekMin, phase, startKey, endKey }
  }, [weekOffset, baseMonday])

  const rangeLabel = `${week.days[0].toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} – ${week.days[6].toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`

  return (
    <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6 lg:p-8">
      <PageHeader
        eyebrow="Training calendar"
        title="Weekly plan"
        subtitle="Planned and completed sessions generated by the engine, colour-coded by discipline."
        actions={
          <div className="flex items-center gap-2">
            <button
              onClick={() => setWeekOffset((o) => o - 1)}
              className="rounded-lg border border-border bg-card p-2 text-foreground transition-colors hover:bg-accent"
              aria-label="Previous week"
            >
              <ChevronLeft className="size-4" />
            </button>
            <button
              onClick={() => setWeekOffset(0)}
              className="rounded-lg border border-border bg-card px-3 py-2 text-sm font-medium transition-colors hover:bg-accent"
            >
              Today
            </button>
            <button
              onClick={() => setWeekOffset((o) => o + 1)}
              className="rounded-lg border border-border bg-card p-2 text-foreground transition-colors hover:bg-accent"
              aria-label="Next week"
            >
              <ChevronRight className="size-4" />
            </button>
          </div>
        }
      />

      {/* Week summary bar */}
      <div className="flex flex-wrap items-center gap-4 rounded-xl border border-border bg-card p-4">
        <div>
          <div className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Week of</div>
          <div className="text-sm font-semibold">{rangeLabel}</div>
        </div>
        {week.phase && (
          <span
            className="inline-flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs font-medium"
            style={{
              backgroundColor: `color-mix(in oklab, ${phaseMeta[week.phase.kind].color} 16%, transparent)`,
              color: phaseMeta[week.phase.kind].color,
            }}
          >
            {week.phase.label} phase
          </span>
        )}
        <div className="ml-auto flex items-center gap-6">
          <div className="text-right">
            <div className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Planned load</div>
            <div className="font-mono text-lg font-semibold tabular-nums">{week.weekTss} TSS</div>
          </div>
          <div className="text-right">
            <div className="font-mono text-xs uppercase tracking-widest text-muted-foreground">Volume</div>
            <div className="font-mono text-lg font-semibold tabular-nums">{formatDuration(week.weekMin)}</div>
          </div>
        </div>
      </div>

      {/* 7 day grid */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-7">
        {week.byDay.map((day) => {
          const isToday = day.key === todayKey
          const isPast = day.key < todayKey
          const weekday = day.date.toLocaleDateString('en-US', { weekday: 'short' })
          const dayNum = day.date.getDate()
          return (
            <div
              key={day.key}
              className={`flex min-h-[220px] flex-col rounded-xl border bg-card ${isToday ? 'border-primary ring-1 ring-primary/40' : 'border-border'}`}
            >
              <div className="flex items-center justify-between border-b border-border px-3 py-2">
                <div className="flex items-baseline gap-1.5">
                  <span className={`text-xs font-medium uppercase ${isToday ? 'text-primary' : 'text-muted-foreground'}`}>
                    {weekday}
                  </span>
                  <span className={`font-mono text-sm font-semibold ${isPast ? 'text-muted-foreground' : ''}`}>
                    {dayNum}
                  </span>
                </div>
                {day.plannedTss > 0 && (
                  <span className="font-mono text-[11px] tabular-nums text-muted-foreground">
                    {isPast ? `${day.doneTss}` : day.plannedTss}
                    <span className="opacity-60"> TSS</span>
                  </span>
                )}
              </div>
              <div className="flex flex-1 flex-col gap-2 p-2">
                {day.items.length === 0 && (
                  <button className="flex flex-1 items-center justify-center rounded-lg border border-dashed border-border text-muted-foreground transition-colors hover:border-ring hover:text-foreground">
                    <Plus className="size-4" />
                  </button>
                )}
                {day.items.map((w) => (
                  <CalendarChip key={w.id} workout={w} />
                ))}
              </div>
            </div>
          )
        })}
      </div>

      <Legend />
    </div>
  )
}

function CalendarChip({ workout }: { workout: Workout }) {
  const meta = sportMeta[workout.sport]
  const done = workout.status === 'completed' && workout.completed
  const missed = workout.status === 'missed'

  if (workout.sport === 'rest') {
    return (
      <div className="rounded-lg border border-dashed border-border px-2.5 py-2 text-center text-xs text-muted-foreground">
        Rest
      </div>
    )
  }

  return (
    <Link
      href={`/workouts/${workout.id}`}
      className="block rounded-lg border border-border p-2 transition-colors hover:border-ring/60 hover:bg-accent/40"
      style={{ borderLeftWidth: 3, borderLeftColor: meta.color }}
    >
      <div className="flex items-center justify-between gap-1">
        <span className="truncate text-xs font-semibold">{workout.title}</span>
        {done && <span className="size-1.5 shrink-0 rounded-full bg-[var(--tsb)]" />}
        {missed && <span className="size-1.5 shrink-0 rounded-full bg-destructive" />}
      </div>
      <div className="mt-1 flex items-center justify-between font-mono text-[11px] text-muted-foreground">
        <span style={{ color: meta.color }}>{meta.short}</span>
        <span>{formatDuration(done ? workout.completed!.durationMin : workout.plannedDurationMin)}</span>
      </div>
      {/* zone strip */}
      <div className="mt-1.5 flex h-1 overflow-hidden rounded-full bg-muted">
        {workout.zoneMinutes.map((m, i) => {
          if (m <= 0) return null
          return (
            <div
              key={i}
              style={{
                width: `${(m / workout.plannedDurationMin) * 100}%`,
                backgroundColor: `var(--zone-${i + 1})`,
                opacity: done ? 1 : 0.55,
              }}
            />
          )
        })}
      </div>
    </Link>
  )
}

function Legend() {
  const sports = ['swim', 'bike', 'run', 'strength'] as const
  return (
    <div className="flex flex-wrap items-center gap-x-5 gap-y-2 rounded-xl border border-border bg-card px-4 py-3 text-xs">
      <span className="font-mono uppercase tracking-widest text-muted-foreground">Discipline</span>
      {sports.map((s) => (
        <span key={s} className="inline-flex items-center gap-1.5">
          <span className="size-2.5 rounded-sm" style={{ backgroundColor: sportMeta[s].color }} />
          {sportMeta[s].label}
        </span>
      ))}
      <span className="ml-auto inline-flex items-center gap-1.5 text-muted-foreground">
        <span className="size-1.5 rounded-full bg-[var(--tsb)]" /> completed
        <span className="ml-3 size-1.5 rounded-full bg-destructive" /> missed
      </span>
    </div>
  )
}
